# Generated by Django 3.2.7 on 2021-10-05 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0002_auto_20211005_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 5, 21, 45, 43, 579881)),
        ),
    ]
