# Generated by Django 3.2.7 on 2021-10-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0004_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='volleyball.transaction'),
        ),
    ]
